services:
  db:
    image: postgres:18.0
    container_name: cinema_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis:8.6.3
    container_name: cinema_redis
    restart: always
    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

  minio:
    image: minio/minio
    container_name: cinema_minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${S3_STORAGE_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_STORAGE_SECRET_KEY}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  celery_worker:
    build: .
    container_name: cinema_celery_worker
    restart: always
    command: celery -A celery_app.worker worker --loglevel=info
    env_file: .env
    depends_on:
      - redis
      - db

  celery_beat:
    build: .
    container_name: cinema_celery_beat
    restart: always
    command: celery -A celery_app.worker beat --loglevel=info
    env_file: .env
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
  minio_data:
  redis_data:

