"""add user_id to comment_likes

Revision ID: 075e386d6de6
Revises: 7e3f0aeee20f
Create Date: 2026-05-31 13:04:09.553239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '075e386d6de6'
down_revision: Union[str, Sequence[str], None] = '7e3f0aeee20f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment_likes', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'comment_likes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment_likes', type_='foreignkey')
    op.drop_column('comment_likes', 'user_id')
    # ### end Alembic commands ###
