"""add movies models and update user model

Revision ID: 668062c359b9
Revises: 993597da6296
Create Date: 2026-05-27 11:35:57.306070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '668062c359b9'
down_revision: Union[str, Sequence[str], None] = '993597da6296'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment_likes', 'is_like')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment_likes', sa.Column('is_like', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
